name: haircuts_barber_aja
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: any
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  intl: 0.19.0
  cached_network_image: 3.3.1
  google_fonts: 6.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

